### ISSUE TITLE
in processing.py

### ISSUE THREAD

**Issue by Logeshwaranb** [anjaeju/MCSP#1]
`t=TicToc()`
shows no module like this in ttictoc 
`make_img_768(bits, width, height, save_path)  # default: 1garm`
there is no function in this name we need to use :
`def make_hash_768(opcode_list, bits, gram):`

**Comment by anjaeju** [comment]
I had been reconstructing this repository but got really busy.
So sorry for uncomfortable usage.
I will edit it by this weekend !

**Comment by Logeshwaranb** [comment]
It's ok

Thanks a lot

**Comment by anjaeju** [comment]
@Logeshwaranb 
Hi, I edited files more readable and easy to use.

If it helps, please close the issue
